### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-go#21]
In this milestone, we focus on cleaning up existing code and make it ready for OpenSearch development

- [x] Remove X-Pack and non oss features/tests
- [x] Remove docs
- [x] Remove commits not related to >7.10 from *main* branch
- [x] Update CI to run with  *OpenDistro* docker image with out security plugin
